# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 15:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True, verbose_name='Course Name')),
                ('course_bio', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course Description')),
                ('course_language', models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi')], max_length=25, verbose_name='Course Language')),
                ('course_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], max_length=20, verbose_name='Course Difficulty')),
                ('course_fees', models.IntegerField(blank=True, help_text='5 digits maximum', null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)], verbose_name='Course Fees')),
                ('course_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Event From')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Event From')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventModuleReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventModules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Module Description')),
                ('module_day', models.IntegerField(blank=True, help_text='2 digits maximum', null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Day when taken')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Time from')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Time to')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.EventModules')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]*$')], verbose_name='First Name')),
                ('user_last_name', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]*$')], verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('user_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('user_github', models.CharField(blank=True, max_length=100, verbose_name='Github Profile')),
                ('user_linkedin', models.CharField(blank=True, max_length=100, verbose_name='Linkedin Profile')),
                ('user_bio', models.CharField(blank=True, max_length=1000, verbose_name='Short Bio')),
                ('user_occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User'),
        ),
        migrations.AddField(
            model_name='eventmodulereview',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.EventModules'),
        ),
        migrations.AddField(
            model_name='eventmodulereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmodulereview',
            unique_together=set([('user', 'module')]),
        ),
    ]
